/**
 * /playground/icons — PWA app-icon curation surface (phase 2.5, slice S1).
 *
 * Throwaway, like /playground/dashboard: renders the icon concepts
 * (generated by scripts/generate-icons.mjs) at home-screen size (~60px),
 * 192px, and a maskable circle-crop worst-case preview, each on BOTH a dark
 * and a light ground, so the user can pick the winner from real pixels.
 *
 * ROUND 3 (v6a–v6c) leads: round-2 feedback picked V6's owl but questioned
 * the gradient ground, so round 3 holds the head/eye geometry and varies the
 * ground (flat, pale-on-flat, muted horizon). The decision-critical view is
 * the HOME SCREEN section up top: true-size 60px candidates on a mock dark
 * wallpaper among dummy app tiles — gradient-vs-flat judged where the icon
 * actually lives. Rounds 2 and 1 stay below for comparison. The wired set
 * (manifest + apple-touch links) is PROVISIONALLY v1 until curation decides;
 * swapping = change WIRED_VARIANT in the script and re-run.
 *
 * The /playground(.*) Clerk exemption in src/proxy.ts already makes this
 * route reachable without auth.
 */
import Image from "next/image";

type Variant = { id: string; label: string; sub: string };

const ROUNDS: { id: string; label: string; sub: string; variants: Variant[] }[] =
  [
    {
      id: "round-3",
      label: "Round 3 — V6 grounds",
      sub: "same owl, different grounds: is it the gradient or the bird?",
      variants: [
        {
          id: "v6a",
          label: "V6a — Flat",
          sub: "elevated-dusk head on the flat dusk ground",
        },
        {
          id: "v6b",
          label: "V6b — Pale",
          sub: "pale head on flat dusk, dusk eye sockets with amber irises",
        },
        {
          id: "v6c",
          label: "V6c — Muted horizon",
          sub: "~80% flat dusk, warm band held to the bottom quarter",
        },
      ],
    },
    {
      id: "round-2",
      label: "Round 2 — owl-forward",
      sub: "eyes, tufts, facial disc: must read owl at 60px",
      variants: [
        {
          id: "v4",
          label: "V4 — Watcher",
          sub: "geometric face: pale eyes, splayed tufts, amber beak",
        },
        {
          id: "v5",
          label: "V5 — Disc",
          sub: "barn-owl heart face: dusk eyes, amber beak",
        },
        {
          id: "v6",
          label: "V6 — Night Watch",
          sub: "tufted head on horizon gradient, amber-glow eyes",
        },
      ],
    },
    {
      id: "round-1",
      label: "Round 1 — emblem-derived (comparison)",
      sub: "seed geometry from the in-app emblem; kept for reference",
      variants: [
        {
          id: "v1",
          label: "V1 — Dusk Perch",
          sub: "2-tone mark on dusk · wired (provisional)",
        },
        {
          id: "v2",
          label: "V2 — First Light",
          sub: "silhouette on horizon gradient",
        },
        { id: "v3", label: "V3 — Sun Disc", sub: "dusk owl in the amber sun" },
      ],
    },
  ];

const GROUNDS = [
  // Dark home screen — the product's own dusk ground. Captions use the
  // muted-foreground token (7.05:1 on --background — WCAG AA ✓).
  {
    id: "dark",
    label: "dark",
    className: "bg-background",
    captionClassName: "text-muted-foreground",
  },
  // Light home screen — no light token is minted (DESIGN.md §2, V2 Pale Dawn
  // is a future slice), so a neutral light ground stands in for iOS/Android
  // light wallpaper. Curation surface only; not product UI. The dusk
  // muted-foreground token only hits 2.43:1 on zinc-100, so this non-token
  // ground carries a matching non-token caption color (zinc-600 → 7.03:1 AA ✓).
  {
    id: "light",
    label: "light",
    className: "bg-zinc-100",
    captionClassName: "text-zinc-600",
  },
] as const;

// --- Home-screen context mock (round 3, decision-critical) -----------------
// Simulates an iOS dark home screen: one wallpaper panel per candidate, the
// candidate at TRUE size (60px, iOS 22% corner radius) labelled "Strix" among
// neutral dummy tiles. Wallpaper, dummy fills, and white labels are inline
// non-token values ON PURPOSE: they imitate the OS environment, not product
// UI (same precedent as the bg-zinc-100 light ground above).
const HOME_CANDIDATES = [
  { id: "v6", label: "V6 — Night Watch (gradient · original)" },
  { id: "v6a", label: "V6a — Flat" },
  { id: "v6b", label: "V6b — Pale" },
  { id: "v6c", label: "V6c — Muted horizon" },
  { id: "v4", label: "V4 — Watcher (reference)" },
];

const WALLPAPER =
  "linear-gradient(165deg, #1c2233 0%, #0c101d 55%, #131725 100%)";

// 7 dummies + the candidate = 4 columns × 2 rows. Grays/dusk tones only —
// no glyphs, so nothing competes with the candidate for attention.
const DUMMY_APPS = [
  { name: "Mail", tone: "#3a4152" },
  { name: "Photos", tone: "linear-gradient(145deg, #48506b, #262b3c)" },
  { name: "Notes", tone: "#23283a" },
  { name: "Camera", tone: "#515868" },
  { name: "Maps", tone: "#2d3242" },
  { name: "Weather", tone: "linear-gradient(160deg, #39415a, #1d2230)" },
  { name: "Files", tone: "#424a5e" },
];

function HomeScreenTile({
  name,
  icon,
}: {
  name: string;
  icon: React.ReactNode;
}) {
  return (
    <div className="flex w-[72px] flex-col items-center gap-1.5">
      {icon}
      <span className="text-[11px] leading-none text-white/90">{name}</span>
    </div>
  );
}

function HomeScreenPanel({ id, label }: { id: string; label: string }) {
  const tiles = DUMMY_APPS.map((d) => (
    <HomeScreenTile
      key={d.name}
      name={d.name}
      icon={
        <div
          className="size-[60px] rounded-[22%]"
          style={{ background: d.tone }}
        />
      }
    />
  ));
  // Candidate sits at row 1, column 2 — embedded among the dummies, not a
  // showcase corner slot.
  tiles.splice(
    1,
    0,
    <HomeScreenTile
      key="strix"
      name="Strix"
      icon={
        <IconCell
          src={`/icons/strix-${id}-192.png`}
          size={60}
          alt={`${label} at true size on the mock home screen`}
        />
      }
    />,
  );
  return (
    <figure className="flex flex-col gap-2">
      <figcaption className="text-sm font-medium text-foreground">
        {label}
      </figcaption>
      <div
        className="w-full max-w-[375px] rounded-2xl border border-border px-4 pb-7 pt-6"
        style={{ background: WALLPAPER }}
      >
        <div className="grid grid-cols-4 justify-items-center gap-y-6">
          {tiles}
        </div>
      </div>
    </figure>
  );
}

function IconCell({
  src,
  size,
  alt,
  circle = false,
}: {
  src: string;
  size: number;
  alt: string;
  circle?: boolean;
}) {
  return (
    <Image
      src={src}
      width={size}
      height={size}
      alt={alt}
      unoptimized
      className={circle ? "rounded-full" : "rounded-[22%]"}
    />
  );
}

export default function PlaygroundIconsPage() {
  return (
    <main className="mx-auto flex w-full max-w-3xl flex-col gap-10 p-6">
      <div className="flex flex-col gap-1">
        <h1 className="font-heading text-2xl font-medium tracking-tight text-foreground">
          App icon curation
        </h1>
        <p className="text-sm text-muted-foreground">
          Icon concepts in the V1 Dusk palette. Home-screen 60px, manifest
          192px, and the maskable circle-crop worst case, on dark and light
          grounds. The standard previews wear the iOS corner mask; launchers
          apply their own.
        </p>
      </div>

      <section aria-label="Home screen" className="flex flex-col gap-6">
        <div className="flex flex-col gap-0.5 border-b border-border pb-2">
          <h2 className="font-heading text-xl font-medium tracking-tight text-foreground">
            Home screen
          </h2>
          <p className="text-xs text-muted-foreground">
            true-size 60px candidates on a mock dark wallpaper among dummy
            apps — judge gradient vs flat where the icon lives
          </p>
        </div>
        <div className="flex flex-col gap-5">
          {HOME_CANDIDATES.map((c) => (
            <HomeScreenPanel key={c.id} id={c.id} label={c.label} />
          ))}
        </div>
      </section>

      {ROUNDS.map((round) => (
        <section
          key={round.id}
          aria-label={round.label}
          className="flex flex-col gap-6"
        >
          <div className="flex flex-col gap-0.5 border-b border-border pb-2">
            <h2 className="font-heading text-xl font-medium tracking-tight text-foreground">
              {round.label}
            </h2>
            <p className="text-xs text-muted-foreground">{round.sub}</p>
          </div>

          {round.variants.map((v) => (
            <section
              key={v.id}
              aria-label={v.label}
              className="flex flex-col gap-3"
            >
              <div className="flex items-baseline gap-2">
                <h3 className="font-heading text-lg font-medium text-foreground">
                  {v.label}
                </h3>
                <span className="text-xs text-muted-foreground">{v.sub}</span>
              </div>

              <div className="flex flex-col gap-px overflow-hidden rounded-lg border border-border">
                {GROUNDS.map((g) => (
                  <div
                    key={g.id}
                    className={`flex flex-wrap items-end gap-x-8 gap-y-4 p-5 ${g.className}`}
                  >
                    <figure className="flex flex-col items-center gap-2">
                      <IconCell
                        src={`/icons/strix-${v.id}-192.png`}
                        size={60}
                        alt={`${v.label} at home-screen size on ${g.label}`}
                      />
                      <figcaption className={`text-[10px] ${g.captionClassName}`}>
                        60px · {g.label}
                      </figcaption>
                    </figure>
                    <figure className="flex flex-col items-center gap-2">
                      <IconCell
                        src={`/icons/strix-${v.id}-192.png`}
                        size={192}
                        alt={`${v.label} at 192px on ${g.label}`}
                      />
                      <figcaption className={`text-[10px] ${g.captionClassName}`}>
                        192px · {g.label}
                      </figcaption>
                    </figure>
                    <figure className="flex flex-col items-center gap-2">
                      <IconCell
                        src={`/icons/strix-${v.id}-maskable-192.png`}
                        size={120}
                        alt={`${v.label} maskable circle-crop preview on ${g.label}`}
                        circle
                      />
                      <figcaption className={`text-[10px] ${g.captionClassName}`}>
                        maskable circle · {g.label}
                      </figcaption>
                    </figure>
                  </div>
                ))}
              </div>
            </section>
          ))}
        </section>
      ))}
    </main>
  );
}
