/**
 * /playground/icons — PWA app-icon curation surface (phase 2.5, slice S1).
 *
 * Throwaway, like /playground/dashboard: renders the THREE icon concepts
 * (generated by scripts/generate-icons.mjs from the canonical owl-mark
 * geometry — DESIGN.md §10) at home-screen size (~60px), 192px, and a
 * maskable circle-crop worst-case preview, each on BOTH a dark and a light
 * ground, so the user can pick the winner from real pixels. The wired set
 * (manifest + apple-touch links) is PROVISIONALLY v1 until this curation
 * pass decides; swapping = change WIRED_VARIANT in the script and re-run.
 *
 * The /playground(.*) Clerk exemption in src/proxy.ts already makes this
 * route reachable without auth.
 */
import Image from "next/image";

const VARIANTS = [
  {
    id: "v1",
    label: "V1 — Dusk Perch",
    sub: "2-tone mark on dusk · wired (provisional)",
  },
  {
    id: "v2",
    label: "V2 — First Light",
    sub: "silhouette on horizon gradient",
  },
  { id: "v3", label: "V3 — Sun Disc", sub: "dusk owl in the amber sun" },
] as const;

const GROUNDS = [
  // Dark home screen — the product's own dusk ground.
  { id: "dark", label: "dark", className: "bg-background" },
  // Light home screen — no light token is minted (DESIGN.md §2, V2 Pale Dawn
  // is a future slice), so a neutral light ground stands in for iOS/Android
  // light wallpaper. Curation surface only; not product UI.
  { id: "light", label: "light", className: "bg-zinc-100" },
] as const;

function IconCell({
  src,
  size,
  alt,
  circle = false,
}: {
  src: string;
  size: number;
  alt: string;
  circle?: boolean;
}) {
  return (
    <Image
      src={src}
      width={size}
      height={size}
      alt={alt}
      unoptimized
      className={circle ? "rounded-full" : "rounded-[22%]"}
    />
  );
}

export default function PlaygroundIconsPage() {
  return (
    <main className="mx-auto flex w-full max-w-3xl flex-col gap-8 p-6">
      <div className="flex flex-col gap-1">
        <h1 className="font-heading text-2xl font-medium tracking-tight text-foreground">
          App icon curation
        </h1>
        <p className="text-sm text-muted-foreground">
          Three concepts from the owl-mark geometry (DESIGN.md §10), V1 Dusk
          palette. Home-screen 60px, manifest 192px, and the maskable
          circle-crop worst case, on dark and light grounds. The standard
          previews wear the iOS corner mask; launchers apply their own.
        </p>
      </div>

      {VARIANTS.map((v) => (
        <section key={v.id} aria-label={v.label} className="flex flex-col gap-3">
          <div className="flex items-baseline gap-2">
            <h2 className="font-heading text-lg font-medium text-foreground">
              {v.label}
            </h2>
            <span className="text-xs text-muted-foreground">{v.sub}</span>
          </div>

          <div className="flex flex-col gap-px overflow-hidden rounded-lg border border-border">
            {GROUNDS.map((g) => (
              <div
                key={g.id}
                className={`flex flex-wrap items-end gap-x-8 gap-y-4 p-5 ${g.className}`}
              >
                <figure className="flex flex-col items-center gap-2">
                  <IconCell
                    src={`/icons/strix-${v.id}-192.png`}
                    size={60}
                    alt={`${v.label} at home-screen size on ${g.label}`}
                  />
                  <figcaption className="text-[10px] text-zinc-500">
                    60px · {g.label}
                  </figcaption>
                </figure>
                <figure className="flex flex-col items-center gap-2">
                  <IconCell
                    src={`/icons/strix-${v.id}-192.png`}
                    size={192}
                    alt={`${v.label} at 192px on ${g.label}`}
                  />
                  <figcaption className="text-[10px] text-zinc-500">
                    192px · {g.label}
                  </figcaption>
                </figure>
                <figure className="flex flex-col items-center gap-2">
                  <IconCell
                    src={`/icons/strix-${v.id}-maskable-192.png`}
                    size={120}
                    alt={`${v.label} maskable circle-crop preview on ${g.label}`}
                    circle
                  />
                  <figcaption className="text-[10px] text-zinc-500">
                    maskable circle · {g.label}
                  </figcaption>
                </figure>
              </div>
            ))}
          </div>
        </section>
      ))}
    </main>
  );
}
